services:
  d:
    # test service for generateInventoryFromProducts.sh
    image: alpine
    volumes:
      - ../../../../:/mnt/WMUI
      - ../../../../../2l-posix-shell-utils:/mnt/pu
      - ./scripts/:/mnt/scripts
      - ./test/:/mnt/test/
    environment:
      - PU_HOME=/mnt/pu
      - WMUI_HOME=/mnt/WMUI
    command: /mnt/scripts/entrypoint.sh
    entrypoint: /mnt/scripts/entrypoint.sh

# Made with Bob
# TODO: move into the unit tests for wmui-functions
