
volumes:
  install-home: {}
  sum-home: {}
  audit: {}
  esdata: {}

networks:
    n1:
      external: false
services:
  apigateway:
    build:
      context: ${H_WMUI_HOME}/09.utils/container-images/ubi/vm-emulator
      args:
        - __audit_home_dir=${WMUI_AUDIT_BASE_DIR}
        - __install_dir=${WMUI_INSTALL_INSTALL_DIR}
        - __upd_mgr_home_dir=${WMUI_UPD_MGR_HOME}
        - __user_home=${WMUI_USER_HOME}
        - __script_dir=${WMUI_TEST_LOCAL_SCRIPTS_DIR}

    image: local/api-gw-1101-default-test-2
    container_name: api-gw-1101-default-test-2
    hostname: api-gw-1101-default-test-2
    ulimits:
      nproc: 4096
      nofile: 65536
    volumes:
      # the following must match the Dockerfile folders, otherwise permissions on FS will not work
      - install-home:${WMUI_INSTALL_INSTALL_DIR}
      - sum-home:${WMUI_UPD_MGR_HOME}
      - audit:${WMUI_AUDIT_BASE_DIR}
      - ./scripts:${WMUI_TEST_LOCAL_SCRIPTS_DIR}
      # These must be provided, they are prerequisites
      - ${H_WMUI_FIXES_IMAGE_FILE}:${WMUI_PATCH_FIXES_IMAGE_FILE}
      - ${H_WMUI_PRODUCTS_IMAGE_FILE}:${WMUI_INSTALL_IMAGE_FILE}
      - ${H_WMUI_UPD_MGR_BOOTSTRAP_BIN}:${WMUI_PATCH_UPD_MGR_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMUI_INSTALLER_BIN}:${WMUI_INSTALL_INSTALLER_BIN_MOUNT_POINT}
      - ../../../../../:${WMUI_HOME}
    environment:
      # we declare WMUI_HOME because we mount it here
      - WMUI_HOME
      # setupFunctions prerequisites map, declared here because provided by host
      - WMUI_INSTALL_INSTALLER_BIN
      - WMUI_INSTALL_IMAGE_FILE
      - WMUI_PATCH_UPD_MGR_BOOTSTRAP_BIN
      - WMUI_PATCH_FIXES_IMAGE_FILE
      - WMUI_INSTALL_INSTALL_DIR
      # declare install dir and SUM dir because they are mounted here
      # setup template specifics - license provided by host
      - WMUI_INSTALL_INSTALLER_BIN_MOUNT_POINT
      - WMUI_PATCH_UPD_MGR_BOOTSTRAP_BIN_MOUNT_POINT
      - WMUI_PATCH_AVAILABLE
      - WMUI_ONLINE_MODE
      - WMUI_SDC_ONLINE_MODE
      - WMUI_DEBUG_ON
      - WMUI_WORK_DIR
      # host related, but still needed
      - H_WMUI_PORT_PREFIX
      # Name and port of the REST interface of the Elasticsearch container / core.
      - apigw_elasticsearch_hosts=core-elasticsearch:9200
      - apigw_elasticsearch_tenantId=core
      # HTTPS enablement.
      - apigw_elasticsearch_https_enabled=false
      # Username and password for Elasticsearch. As standard leave it blank.
      - apigw_elasticsearch_http_username=${PROVIDED_ELASTIC_USERNAME}
      - apigw_elasticsearch_http_password=${PROVIDED_ELASTIC_PASSWORD}

      # Name and port of the REST interface of the Elasticsearch container / analytics.
      - apigw_analyticsDataStore_hosts=core-elasticsearch:9200
      - apigw_analyticsDataStore_tenantId=analytics
      # HTTPS enablement.
      - apigw_analyticsDataStore_https_enabled=false
      # Username and password for Elasticsearch. As standard leave it blank.
      - apigw_analyticsDataStore_http_username=${PROVIDED_ELASTIC_USERNAME}
      - apigw_analyticsDataStore_http_password=${PROVIDED_ELASTIC_PASSWORD}

      # external kibana
      - apigw_kibana_dashboardInstance=http://host.docker.internal:${H_WMUI_PORT_PREFIX}56
      # - apigw_kibana_autostart=false
      - WMUI_TEST_LOCAL_SCRIPTS_DIR
      - WMUI_UPD_MGR_HOME

    ports:
      - "${H_WMUI_PORT_PREFIX}73:9073"
      - "${H_WMUI_PORT_PREFIX}72:9072"
      - "${H_WMUI_PORT_PREFIX}55:5555"
    networks:
      n1:
        aliases:
          - apigw-server
    entrypoint: ${WMUI_TEST_LOCAL_SCRIPTS_DIR}/containerEntrypoint.sh
    healthcheck:
      interval: 10s
      retries: 200
      test: curl -u 'Administrator:manage' --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5555/rest/apigateway/health

  core-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${CORE_ELK_VERSION}
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # Used for cluster bootstrapping. The mentioned nodes are potential master nodes.
      # - cluster.initial_master_nodes=core-elasticsearch
      # got this from the elasticvue hints
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/ # This is as large as possible, the lab is supposed to work locally only. Eventually enforce as needed
      - ELASTIC_USERNAME=${PROVIDED_ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${PROVIDED_ELASTIC_PASSWORD}
    ports:
      # REST interface
      - ${H_WMUI_PORT_PREFIX}20:9200
    networks:
      - n1
    # Compute resources
    mem_reservation: 1g 
    mem_limit: 1g # seems 1g is sufficient to start a small one, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    cpus: 1
    # kernel / namespace limits
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
  
  # Elasticvue content explorer for elasticsearch, use for observability reasons
  elasticvue:
    image: cars10/elasticvue
    ports:
      - "${H_WMUI_PORT_PREFIX}80:8080"
    networks:
      - n1
    depends_on:
      core-elasticsearch:
        condition: service_healthy
    mem_reservation: 100m
    mem_limit: 500m
    cpus: 1
  
  core-kibana:
    image: docker.elastic.co/kibana/kibana:${CORE_ELK_VERSION}
    depends_on:
      #core-elasticsearch:
      #  condition: service_healthy
      apigateway:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=http://core-elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://core-elasticsearch:9200
      - KIBANA_EXTERNAL_HOSTNAME=http://host.docker.internal:${H_WMUI_PORT_PREFIX}56
      - ELASTICSEARCH_USERNAME=${PROVIDED_ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${PROVIDED_ELASTIC_PASSWORD}
      - SERVER_BASEPATH=/apigatewayui/dashboardproxy
      - CONSOLE_ENABLED=false
      #- KIBANA_INDEX=gateway_default_dashboard
    ports:
    - ${H_WMUI_PORT_PREFIX}56:5601
    networks:
    - n1
    healthcheck:
      interval: 10s
      retries: 400
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
    # Compute resource limits
    mem_reservation: 200m
    mem_limit: 1g # seems 1g is sufficient to start a small one, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    cpus: 1
  